services:
  app:
    build: .
    ports:
      - "5100:5100"
    volumes:
      - model-cache:/root/.cache  # Cache all AI model files and libraries
      - torch-cache:/root/.cache/torch  # Specific cache for PyTorch models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  model-cache:
  torch-cache:
