services:
  app:
    build: .
    ports:
      - "5100:5100"
    volumes:
      - huggingface-cache:/root/.cache/huggingface/transformers
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  huggingface-cache:
